module HROOT.Generate.ROOTModule where

exposedModules :: [String]
exposedModules = [ "HROOT" 
                 , "HROOT.Class.Interface"
                 , "HROOT.Class.Implementation"
                 , "HROOT.Class.FFI"
                 , "HROOT.Class.Existential"
                 , "HROOT.AddOn" 
                 , "HROOT.AddOnFunction" ]

{-
classModules :: [String]
classModules = [ "TObject"
               , "TNamed"
               , "TClass"
               , "TDictionary"
               , "TCanvas"
               , "TAttCanvas"
               , "TH1"
               , "TH1F" ]
-}

classModules :: [String] 
classModules = [ "TObject" 
               , "TNamed" 
               , "TDictionary"
               , "TClass"
               , "TFormula"
               , "TAtt3D"
               , "TAttAxis"
               , "TAttBBox"
               , "TAttCanvas"
               , "TAttFill"
               , "TAttImage"
               , "TAttLine"
               , "TAttMarker"
               , "TAttPad"
               , "TAttParticle"
               , "TAttText"
               , "THStack"
               , "TF1"
               , "TGraph"
               , "TGraphAsymmErrors"
               , "TCutG"
               , "TGraphBentErrors"
               , "TGraphErrors"
               , "TGraphPolar"
               , "TGraphQQ"
               , "TEllipse"
               , "TArc"
               , "TCrown"
               , "TLine"
               , "TArrow"
               , "TGaxis"
               , "TShape"
               , "TBRIK"
               , "TTUBE"
               , "TPCON"
               , "TSPHE"
               , "TXTRU"
               , "TBox"
               , "TPave"
               , "TPaveText"
               , "TDiamond"
               , "TPaveStats"
               , "TPavesText"
               , "TLegend"
               , "TPaveLabel"
               , "TPaveClass"
               , "TWbox"
               , "TFrame"
               , "TSliderBox"
               , "TTree"
               , "TChain"
               , "TNtuple"
               , "TNtupleD"
               , "TTreeSQL"
               , "TPolyLine"
               , "TCurlyLine"
               , "TCurlyArc"
               , "TEfficiency"
               , "TAxis"
               , "TLatex"
               , "TText"
               , "TDirectory"
               , "TDirectoryFile"
               , "TFile"
               , "TBranch"
               , "TVirtualTreePlayer"
               , "TTreePlayer"
               , "TArray"
               , "TArrayC"
               , "TArrayD"
               , "TArrayF"
               , "TArrayI"
               , "TArrayL"
               , "TArrayL64"
               , "TArrayS"
               , "TH1"
               , "TH2"
               , "TH3"
               , "TH1C"
               , "TH1D"
               , "TH1F"
               , "TH1I"
               , "TH1S"
               , "TH2C"
               , "TH2D"
               , "TH2F"
               , "TH2I"
               , "TH2Poly"
               , "TH2S"
               , "TH3C"
               -- , "TProfile"
               , "TCollection"
               , "TSeqCollection"
               , "TObjArray"
               , "TList"
               , "TKey"
               , "TDatime"
               , "TVirtualHistPainter"
               ]
