# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci

    environment:
      NIXPKGS_REV: b9948763f54d1ad7710f93d7d5a5365f8739afd3

    working_directory: ~/repo

    steps:
      - checkout

      - "run":
          name: "Prepare For Cache Key"
          command: |
            echo "${NIXPKGS_REV}" > nixpkgs.rev

      # Download and cache dependencies
      - restore_cache:
          name: "Restore Nix Store Paths"
          keys:
            - v1-dependencies-{{ checksum "nixpkgs.rev" }}
            - v1-dependencies-

      - run:
          name: Setup NIX_PATH Environment Variable
          command: |
            echo "export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/$NIXPKGS_REV.tar.gz" >> $BASH_ENV

      - run:
          name: Build
          command: |
            nix-build release.nix

      - save_cache:
          paths:
            - /nix
          key: v1-dependencies-{{ checksum "nixpkgs.rev" }}
