name: "Build"
on: [pull_request, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: check flake
      run: |
        nix flake check
    - name: build fficxx-runtime
      run: |
        nix build --print-build-logs .#fficxx-runtime
    - name: build fficxx
      run: |
        nix build --print-build-logs .#fficxx
    - name: build stdcxx
      run: |
        nix build --print-build-logs .#stdcxx
    - name: build fficxx-test
      run: |
        nix build --print-build-logs .#fficxx-test
    - name: build fficxx-multipkg-test
      run: |
        nix build --print-build-logs .#fficxx-multipkg-test
    - name: build tmf-test
      run: |
        nix build --print-build-logs .#tmf-test
    - name: build tmpl-dep-test
      run: |
        nix build --print-build-logs .#tmpl-dep-test
    - name: build tmpl-dup-inst
      run: |
        nix build --print-build-logs .#tmpl-dup-inst
    - name: build tmpl-toplevel-test
      run: |
        nix build --print-build-logs .#tmpl-toplevel-test
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # ormolu 0.3.0.1
      - uses: mrkkrp/ormolu-action@v4
