name: "Build"
on: [pull_request, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: build fficxx-runtime (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.fficxx-runtime
    - name: build fficxx (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.fficxx
    - name: build stdcxx (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.stdcxx
    - name: build fficxx-test (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.fficxx-test
    - name: build fficxx-multipkg-test (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.fficxx-multipkg-test
    - name: build tmf-test (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.tmf-test
    - name: build tmpl-dep-test (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.tmpl-dep-test
    - name: build tmpl-dup-inst (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.tmpl-dup-inst
    - name: build tmpl-toplevel-test (GHC 9.6.2)
      run: |
        nix build --print-build-logs .#ghc962.tmpl-toplevel-test
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # ormolu 0.5.0.1
      - uses: mrkkrp/ormolu-action@v14
        with:
          version: 0.5.0.1